version: "0.0.1"
services:
  data-review-tool:
    build: 
      dockerfile: ./docker/data-review-tool/Dockerfile
      context: .
    ports:
      - "8050:8050"
    volumes:
    - ./data/data-review-tool:/MetaExtractor/data/data-review-tool
    # environment:
    #   - USE_NER_MODEL_TYPE=spacy