version: "0.0.1"
services:
  entity-extraction-pipeline:
    build: 
      dockerfile: ./docker/entity-extraction-pipeline/Dockerfile
      context: .
      args:
        HF_NER_MODEL_NAME: "roberta-finetuned-v3"
        SPACY_NER_MODEL_NAME: "spacy-transformer-v3"
    ports:
      - "5000:5000"
    volumes:
    - ./data/entity-extraction/raw/original_files/sentences_nlp352:/app/inputs/sentences_nlp352
    - ./data/entity-extraction/processed/processed_articles/:/app/outputs/
    # load .env file from docker/entity-extraction-pipeline folder
    environment:
      - USE_NER_MODEL_TYPE=spacy
      - LOG_OUTPUT_DIR=/app/outputs/


  